# Generated by Django 5.1.7 on 2025-04-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='ai_provider',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='has_ai',
        ),
    ]
