# Generated by Django 5.1.7 on 2025-04-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_conversation_ai_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='encrypted_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_content',
            new_name='content',
        ),
        migrations.DeleteModel(
            name='EncryptionKey',
        ),
    ]
