# Generated by Django 5.1.7 on 2025-04-13 14:23

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anthropic_api_key',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='openai_api_key',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
